spring.application.name=nmcnpm_20242_n3
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${DB_PASSWORD:admin}
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:create}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Create table before propagating to the database
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=${SQL_INIT_MODE:always}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.data-locations=classpath:data-postgres.sql
spring.jpa.show-sql=${SHOW_SQL:true}

management.metrics.export.statsd.enabled=true
management.metrics.export.statsd.flavor=etsy
management.metrics.export.statsd.host=${STATSD_HOST:localhost}
management.metrics.export.statsd.port=8125
